version: '3.8'
services:
  blog_api:
    image: mcr.microsoft.com/devcontainers/go:1-1.22-bullseye
    container_name: blog-api
    network_mode: service:db
    volumes:
      - ../..:/workspaces:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
  db:
    image: mongo
    container_name: blog-dev-db
    ports:
      - "27012:27017"
    volumes:
      - database:/var/lib/mongo/data
volumes:
  database:
